# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'gradientposTests' do
    testing_pods
end

target 'gradientpos' do
    pod 'Alamofire'
    pod 'ObjectMapper'
	pod 'SwiftyJSON'
	pod 'CryptoSwift'
	pod 'Fabric'
	pod 'Crashlytics'
    pod 'Google/Analytics'
end
